import { Achievement } from '../types';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_workout',
    name: 'Primer Paso',
    description: 'Completa tu primer entrenamiento',
    icon: '🏃',
    condition: { type: 'workouts_completed', count: 1 },
  },
  {
    id: 'five_workouts',
    name: 'En Racha',
    description: 'Completa 5 entrenamientos',
    icon: '💪',
    condition: { type: 'workouts_completed', count: 5 },
  },
  {
    id: 'ten_workouts',
    name: 'Imparable',
    description: 'Completa 10 entrenamientos',
    icon: '🔥',
    condition: { type: 'workouts_completed', count: 10 },
  },
  {
    id: 'twentyfive_workouts',
    name: 'Atleta',
    description: 'Completa 25 entrenamientos',
    icon: '🏆',
    condition: { type: 'workouts_completed', count: 25 },
  },
  {
    id: 'fifty_workouts',
    name: 'Leyenda del Fitness',
    description: 'Completa 50 entrenamientos',
    icon: '👑',
    condition: { type: 'workouts_completed', count: 50 },
  },
  {
    id: 'streak_3',
    name: 'Tres en Línea',
    description: 'Mantén una racha de 3 días',
    icon: '⚡',
    condition: { type: 'streak', days: 3 },
  },
  {
    id: 'streak_7',
    name: 'Semana Perfecta',
    description: 'Mantén una racha de 7 días',
    icon: '🌟',
    condition: { type: 'streak', days: 7 },
  },
  {
    id: 'streak_14',
    name: 'Dos Semanas Fuerte',
    description: 'Mantén una racha de 14 días',
    icon: '💎',
    condition: { type: 'streak', days: 14 },
  },
  {
    id: 'streak_30',
    name: 'Hábito Formado',
    description: 'Mantén una racha de 30 días',
    icon: '🏅',
    condition: { type: 'streak', days: 30 },
  },
  {
    id: 'first_weight',
    name: 'Control Inicial',
    description: 'Registra tu primer peso',
    icon: '⚖️',
    condition: { type: 'weight_entries', count: 1 },
  },
  {
    id: 'seven_weights',
    name: 'Seguimiento Semanal',
    description: 'Registra tu peso 7 veces',
    icon: '📊',
    condition: { type: 'weight_entries', count: 7 },
  },
  {
    id: 'thirty_weights',
    name: 'Constancia de Datos',
    description: 'Registra tu peso 30 veces',
    icon: '📈',
    condition: { type: 'weight_entries', count: 30 },
  },
  {
    id: 'first_food',
    name: 'Primer Registro',
    description: 'Registra tu primer alimento',
    icon: '🍽️',
    condition: { type: 'food_entries', count: 1 },
  },
  {
    id: 'food_tracker_7',
    name: 'Dieta Consciente',
    description: 'Registra 7 alimentos',
    icon: '🥗',
    condition: { type: 'food_entries', count: 7 },
  },
  {
    id: 'food_tracker_30',
    name: 'Nutricionista',
    description: 'Registra 30 alimentos',
    icon: '🧑‍🍳',
    condition: { type: 'food_entries', count: 30 },
  },
  {
    id: 'xp_500',
    name: 'Acumulador',
    description: 'Consigue 500 XP en total',
    icon: '✨',
    condition: { type: 'xp_total', amount: 500 },
  },
  {
    id: 'xp_1000',
    name: 'Mil Puntos',
    description: 'Consigue 1000 XP en total',
    icon: '🎯',
    condition: { type: 'xp_total', amount: 1000 },
  },
  {
    id: 'level_5',
    name: 'Nivel Dedicado',
    description: 'Alcanza el nivel 5',
    icon: '🎖️',
    condition: { type: 'level_reached', level: 5 },
  },
  {
    id: 'level_10',
    name: 'Maestro Supremo',
    description: 'Alcanza el nivel 10',
    icon: '🏆',
    condition: { type: 'level_reached', level: 10 },
  },
];
