import { ExerciseRoutine } from '../types';

export const EXERCISE_ROUTINES: ExerciseRoutine[] = [
  // === PRINCIPIANTE ===
  {
    id: 'beginner_fullbody',
    name: 'Cuerpo Completo Básico',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    xpReward: 30,
    exercises: [
      { id: 'b1_1', name: 'Sentadillas', description: 'De pie, baja las caderas como si te sentaras en una silla. Mantén la espalda recta.', durationSeconds: 30, restSeconds: 15 },
      { id: 'b1_2', name: 'Flexiones de rodillas', description: 'Apoya las rodillas en el suelo y haz flexiones manteniendo el cuerpo alineado.', durationSeconds: 30, restSeconds: 15 },
      { id: 'b1_3', name: 'Plancha', description: 'Mantén el cuerpo recto apoyado en antebrazos y puntas de los pies.', durationSeconds: 20, restSeconds: 15 },
      { id: 'b1_4', name: 'Zancadas alternas', description: 'Da un paso al frente y baja la rodilla trasera. Alterna piernas.', durationSeconds: 30, restSeconds: 15 },
      { id: 'b1_5', name: 'Elevación de talones', description: 'De pie, sube y baja los talones para trabajar los gemelos.', durationSeconds: 30, restSeconds: 15 },
      { id: 'b1_6', name: 'Puente de glúteos', description: 'Tumbado boca arriba, eleva la cadera apretando los glúteos.', durationSeconds: 30, restSeconds: 10 },
    ],
  },
  {
    id: 'beginner_cardio',
    name: 'Cardio Suave',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    xpReward: 30,
    exercises: [
      { id: 'b2_1', name: 'Marcha en el sitio', description: 'Camina en el sitio levantando bien las rodillas.', durationSeconds: 40, restSeconds: 15 },
      { id: 'b2_2', name: 'Paso lateral', description: 'Da pasos laterales alternando derecha e izquierda.', durationSeconds: 30, restSeconds: 15 },
      { id: 'b2_3', name: 'Rodillas al pecho', description: 'Eleva las rodillas al pecho alternando piernas a ritmo moderado.', durationSeconds: 30, restSeconds: 15 },
      { id: 'b2_4', name: 'Talones al glúteo', description: 'Lleva los talones al glúteo alternando piernas.', durationSeconds: 30, restSeconds: 15 },
      { id: 'b2_5', name: 'Tijeras de brazos', description: 'Abre y cierra los brazos cruzándolos frente al pecho.', durationSeconds: 30, restSeconds: 10 },
    ],
  },
  {
    id: 'beginner_stretch',
    name: 'Estiramientos y Flexibilidad',
    difficulty: 'beginner',
    estimatedMinutes: 10,
    xpReward: 30,
    exercises: [
      { id: 'b3_1', name: 'Estiramiento de cuello', description: 'Inclina la cabeza hacia cada lado manteniéndola 10 segundos.', durationSeconds: 30, restSeconds: 10 },
      { id: 'b3_2', name: 'Círculos de hombros', description: 'Haz círculos grandes con los hombros hacia adelante y atrás.', durationSeconds: 30, restSeconds: 10 },
      { id: 'b3_3', name: 'Toque de pies', description: 'De pie, inclínate y toca las puntas de los pies. Mantén la posición.', durationSeconds: 30, restSeconds: 10 },
      { id: 'b3_4', name: 'Estiramiento de cuádriceps', description: 'De pie, lleva el talón al glúteo y mantén. Alterna piernas.', durationSeconds: 30, restSeconds: 10 },
      { id: 'b3_5', name: 'Gato-vaca', description: 'A cuatro patas, arquea y redondea la espalda alternando.', durationSeconds: 30, restSeconds: 10 },
    ],
  },
  // === INTERMEDIO ===
  {
    id: 'intermediate_strength',
    name: 'Fuerza Intermedia',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    xpReward: 50,
    exercises: [
      { id: 'i1_1', name: 'Flexiones', description: 'Flexiones completas con el cuerpo extendido. Baja hasta casi tocar el suelo.', durationSeconds: 40, restSeconds: 20 },
      { id: 'i1_2', name: 'Sentadillas con salto', description: 'Haz una sentadilla y al subir da un pequeño salto.', durationSeconds: 35, restSeconds: 20 },
      { id: 'i1_3', name: 'Plancha lateral', description: 'Apóyate en un antebrazo de lado. Mantén la cadera elevada. Alterna lados.', durationSeconds: 40, restSeconds: 20 },
      { id: 'i1_4', name: 'Zancadas con salto', description: 'Realiza zancadas alternando piernas con un salto en la transición.', durationSeconds: 35, restSeconds: 20 },
      { id: 'i1_5', name: 'Superman', description: 'Tumbado boca abajo, eleva brazos y piernas simultáneamente.', durationSeconds: 30, restSeconds: 15 },
      { id: 'i1_6', name: 'Dips en silla', description: 'Con las manos en una silla, baja y sube el cuerpo flexionando los codos.', durationSeconds: 35, restSeconds: 20 },
      { id: 'i1_7', name: 'Mountain climbers', description: 'En posición de plancha, lleva las rodillas al pecho alternando rápidamente.', durationSeconds: 35, restSeconds: 15 },
    ],
  },
  {
    id: 'intermediate_core',
    name: 'Core y Abdominales',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    xpReward: 50,
    exercises: [
      { id: 'i2_1', name: 'Crunch abdominal', description: 'Tumbado boca arriba, eleva los hombros del suelo contrayendo el abdomen.', durationSeconds: 35, restSeconds: 15 },
      { id: 'i2_2', name: 'Bicicleta', description: 'Tumbado, alterna codo con rodilla opuesta en movimiento de pedaleo.', durationSeconds: 35, restSeconds: 15 },
      { id: 'i2_3', name: 'Plancha', description: 'Mantén la posición de plancha con el cuerpo completamente recto.', durationSeconds: 40, restSeconds: 15 },
      { id: 'i2_4', name: 'Elevación de piernas', description: 'Tumbado boca arriba, eleva las piernas juntas hasta 90 grados.', durationSeconds: 30, restSeconds: 15 },
      { id: 'i2_5', name: 'Russian twist', description: 'Sentado con el torso inclinado, gira el torso de lado a lado.', durationSeconds: 35, restSeconds: 15 },
      { id: 'i2_6', name: 'Dead bug', description: 'Tumbado, extiende brazo y pierna opuestos alternando. Mantén la espalda pegada al suelo.', durationSeconds: 35, restSeconds: 10 },
    ],
  },
  {
    id: 'intermediate_cardio',
    name: 'Cardio Intenso',
    difficulty: 'intermediate',
    estimatedMinutes: 18,
    xpReward: 50,
    exercises: [
      { id: 'i3_1', name: 'Jumping jacks', description: 'Salta abriendo piernas y brazos y vuelve a la posición inicial.', durationSeconds: 40, restSeconds: 20 },
      { id: 'i3_2', name: 'Rodillas al pecho rápidas', description: 'Eleva las rodillas al pecho a máxima velocidad.', durationSeconds: 35, restSeconds: 20 },
      { id: 'i3_3', name: 'Skaters', description: 'Salta lateralmente de un pie a otro, como un patinador.', durationSeconds: 35, restSeconds: 20 },
      { id: 'i3_4', name: 'Burpees suaves', description: 'Baja al suelo, haz una flexión, levántate y da un pequeño salto.', durationSeconds: 30, restSeconds: 25 },
      { id: 'i3_5', name: 'Mountain climbers', description: 'Desde plancha, lleva rodillas al pecho rápidamente.', durationSeconds: 35, restSeconds: 15 },
    ],
  },
  // === AVANZADO ===
  {
    id: 'advanced_hiit',
    name: 'HIIT Total',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    xpReward: 80,
    exercises: [
      { id: 'a1_1', name: 'Burpees', description: 'Burpee completo: baja, flexión, sube y salta con brazos arriba.', durationSeconds: 40, restSeconds: 20 },
      { id: 'a1_2', name: 'Sentadillas con salto', description: 'Sentadilla profunda seguida de salto explosivo.', durationSeconds: 40, restSeconds: 20 },
      { id: 'a1_3', name: 'Flexiones diamante', description: 'Flexiones con las manos juntas formando un diamante.', durationSeconds: 35, restSeconds: 20 },
      { id: 'a1_4', name: 'Jumping lunges', description: 'Zancadas con salto alternando piernas en el aire.', durationSeconds: 35, restSeconds: 20 },
      { id: 'a1_5', name: 'Plancha con toque de hombro', description: 'En plancha, toca el hombro opuesto con cada mano alternando.', durationSeconds: 35, restSeconds: 20 },
      { id: 'a1_6', name: 'Tuck jumps', description: 'Salta llevando las rodillas al pecho en cada salto.', durationSeconds: 30, restSeconds: 25 },
      { id: 'a1_7', name: 'Mountain climbers rápidos', description: 'Mountain climbers a máxima velocidad.', durationSeconds: 40, restSeconds: 20 },
      { id: 'a1_8', name: 'Flexiones con palmada', description: 'Flexiones explosivas dando una palmada en el aire.', durationSeconds: 30, restSeconds: 15 },
    ],
  },
  {
    id: 'advanced_strength',
    name: 'Fuerza Avanzada',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    xpReward: 80,
    exercises: [
      { id: 'a2_1', name: 'Flexiones pike', description: 'Flexiones con la cadera elevada, enfocando hombros.', durationSeconds: 35, restSeconds: 20 },
      { id: 'a2_2', name: 'Pistol squat asistida', description: 'Sentadilla a una pierna usando un soporte para equilibrio.', durationSeconds: 40, restSeconds: 25 },
      { id: 'a2_3', name: 'Dips en silla profundos', description: 'Dips con mayor rango de movimiento y piernas extendidas.', durationSeconds: 35, restSeconds: 20 },
      { id: 'a2_4', name: 'Puente de glúteos a una pierna', description: 'Puente de glúteos elevando una pierna. Alterna.', durationSeconds: 35, restSeconds: 20 },
      { id: 'a2_5', name: 'Flexiones archer', description: 'Flexiones con un brazo extendido al lado, alternando.', durationSeconds: 35, restSeconds: 25 },
      { id: 'a2_6', name: 'Plancha con extensión', description: 'En plancha, extiende un brazo hacia adelante alternando.', durationSeconds: 35, restSeconds: 20 },
      { id: 'a2_7', name: 'Sentadilla búlgara', description: 'Con un pie elevado detrás, haz sentadillas profundas. Alterna.', durationSeconds: 40, restSeconds: 20 },
    ],
  },
  {
    id: 'advanced_tabata',
    name: 'Tabata Extremo',
    difficulty: 'advanced',
    estimatedMinutes: 20,
    xpReward: 80,
    exercises: [
      { id: 'a3_1', name: 'Burpees', description: 'Burpees completos a máxima intensidad.', durationSeconds: 20, restSeconds: 10 },
      { id: 'a3_2', name: 'Sentadillas con salto', description: 'Sentadillas explosivas con salto.', durationSeconds: 20, restSeconds: 10 },
      { id: 'a3_3', name: 'Flexiones explosivas', description: 'Flexiones rápidas y potentes.', durationSeconds: 20, restSeconds: 10 },
      { id: 'a3_4', name: 'Mountain climbers', description: 'A máxima velocidad.', durationSeconds: 20, restSeconds: 10 },
      { id: 'a3_5', name: 'Jumping jacks', description: 'Lo más rápido posible.', durationSeconds: 20, restSeconds: 10 },
      { id: 'a3_6', name: 'Plancha con salto', description: 'Desde plancha, salta los pies hacia las manos y vuelve.', durationSeconds: 20, restSeconds: 10 },
      { id: 'a3_7', name: 'Tuck jumps', description: 'Saltos llevando rodillas al pecho.', durationSeconds: 20, restSeconds: 10 },
      { id: 'a3_8', name: 'Sprint en el sitio', description: 'Corre en el sitio a máxima velocidad.', durationSeconds: 20, restSeconds: 10 },
    ],
  },
];
